name: issues
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Install FAQtory
        run: pip install FAQtory
      - name: Run Suggest
        env:
          TITLE: ${{ github.event.issue.title }}
        run: faqtory suggest "$TITLE" > suggest.md   
      - name: Read suggest.md
        id: suggest
        uses: juliangruber/read-file-action@v1
        with:
          path: ./suggest.md
      - name: Suggest FAQ
        uses: peter-evans/create-or-update-comment@c6c9a1a66007646a28c153e2a8580a5bad27bcfa
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.suggest.outputs.content }}
